[[redirects]]
from ='/*'
to ='index.html'
force = true
status=200


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
